'use strict';
const $=id=>document.getElementById(id),audio=$('music'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let effects=!reduced.matches;
function musicState(){const playing=!audio.paused;$('music-button').setAttribute('aria-pressed',String(playing));$('music-button').setAttribute('aria-label',playing?'Pausar música':'Reproducir música');$('music-icon').textContent=playing?'Ⅱ':'♫'}
audio.addEventListener('play',musicState);audio.addEventListener('pause',musicState);$('music-button').addEventListener('click',()=>audio.paused?audio.play().catch(musicState):audio.pause());
function effectState(){document.body.classList.toggle('effects-off',!effects);$('effects-button').setAttribute('aria-pressed',String(effects));$('effects-button').setAttribute('aria-label',effects?'Pausar destellos':'Activar destellos')}
effectState();$('effects-button').addEventListener('click',()=>{effects=!effects;effectState()});
$('open').addEventListener('click',()=>{$('open').disabled=true;audio.volume=.65;audio.play().catch(musicState);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;$('controls').hidden=false;document.body.classList.remove('sealed');window.scrollTo(0,0);document.querySelector('.hero h2').focus({preventScroll:true});if('IntersectionObserver'in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}},reduced.matches?0:900)});
for(let i=0;i<44;i++){const el=document.createElement('span');el.className=i<30?'glint':'confetti';el.textContent=i<30?(i%3?'✦':'✧'):'';el.style.cssText=`--x:${(i*37+5)%100}%;--y:${(i*23+8)%100}%;--size:${9+i%5*3}px;--speed:${i<30?3+i%5*.8:14+i%9}s;--delay:${-i*1.4}s`;$('sparkles').append(el)}
function countdown(){const diff=new Date('2026-10-16T16:00:00-04:00')-Date.now();if(diff<=0){$('countdown').textContent='¡Llegó el momento de celebrar!';return}const values=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];$('countdown').innerHTML=values.map((n,i)=>`<div><strong>${String(n).padStart(2,'0')}</strong><span>${['DÍAS','HORAS','MINUTOS','SEGUNDOS'][i]}</span></div>`).join('')}
countdown();setInterval(countdown,1000);
$('copy-address').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('Restaurante La Esclava · Martín Cárdenas 0262, Cochabamba. https://maps.app.goo.gl/NMVwmubhzWETcKiG6');$('copy-status').textContent='Dirección copiada. ¡Nos vemos allí!'}catch{$('copy-status').textContent='Martín Cárdenas 0262, Cochabamba. Puedes usar Cómo llegar.'}});
$('back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'}));
$('share').addEventListener('click',async()=>{if(['localhost','127.0.0.1'].includes(location.hostname)||location.protocol==='file:'){$('share-status').textContent='Disponible cuando la invitación tenga su enlace público.';return}const data={title:'Estefani · Mi graduación',text:'Un logro es aún más especial cuando se comparte. Te invito a celebrar conmigo. ♡',url:location.href.split('#')[0]};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.text+' '+data.url);$('share-status').textContent='Invitación copiada para compartir.'}}catch(e){if(e.name!=='AbortError')$('share-status').textContent='Puedes copiar el enlace de la invitación desde tu navegador.'}});
