'use strict';
const $=id=>document.getElementById(id),audio=$('music'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let effects=!reduced.matches;
function musicState(){const playing=!audio.paused;$('music-button').setAttribute('aria-pressed',String(playing));$('music-button').setAttribute('aria-label',playing?'Pausar música':'Reproducir música');$('music-icon').textContent=playing?'Ⅱ':'♫'}
audio.addEventListener('play',musicState);audio.addEventListener('pause',musicState);$('music-button').addEventListener('click',()=>audio.paused?audio.play().catch(musicState):audio.pause());
$('open').addEventListener('click',()=>{$('open').disabled=true;audio.volume=.65;audio.play().catch(musicState);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;$('controls').hidden=false;document.body.classList.remove('sealed');window.scrollTo(0,0);document.querySelector('.hero h2').focus({preventScroll:true});if('IntersectionObserver'in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}},reduced.matches?0:900)});
for(let i=0;i<12;i++){const el=document.createElement('span');el.className='glint';el.textContent=i<30?(i%3?'✦':'✧'):'';el.style.cssText=`--x:${(i*37+5)%100}%;--y:${(i*23+8)%100}%;--size:${9+i%5*3}px;--speed:${i<30?3+i%5*.8:14+i%9}s;--delay:${-i*1.4}s`;$('sparkles').append(el)}
function countdown(){const diff=new Date('2026-10-16T17:30:00-04:00')-Date.now();if(diff<=0){$('countdown').textContent='¡Llegó el momento de celebrar!';return}const values=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];$('countdown').innerHTML=values.map((n,i)=>`<div><strong>${String(n).padStart(2,'0')}</strong><span>${['DÍAS','HORAS','MINUTOS','SEGUNDOS'][i]}</span></div>`).join('')}
countdown();setInterval(countdown,1000);
